### ISSUE TITLE
[RFE] Please provide a REST API or similar

### ISSUE THREAD

**Issue by q2dg** [draios/sysdig-inspect#44]
Hello.
I want to use sysdig-inspect in my server systems but I haven't any graphical environment there, so I'd just want to open a browser from any graphical client machine to get into sysdig-inspect's front page.
Is it possible?
Thanks!

**Comment by mfdii** [comment]
Sysdig Inspect is not meant to be ran on server systems to display data in real time. Rather, you should create a capture on the server using `sysdig`, copy that capture back to a workstation, then open the capture with Sysdig Inspect. This is similar to the workflow you would use with `tcpdump` and Wireshark. 

If you really need to use Sysdig Inspect on the server (because you can't copy the capture), you can use an experimental container. This isn't supported and your success may vary. 

```
$ mkdir captures
# copy any captures to the captures directory
$ docker run -p 4200:4200 -p 3000:3000 -v $(pwd)/captures:/tmp/captures sysdiglabs/sysdig-inspect
```

If you browse to http://<server:4200> you should have the Sysdig Inspect UI. You can enter `/tmp/captures/<your capture file>.scap` in the text box and hit enter. Inspect should load the capture. I've had varied success with this so it may not work.

**Comment by q2dg** [comment]
Thanks a lot for your detailed answer. 
Your proposed solution is fine for me so I'll close the issue, if you don't mind.
Thanks!
